---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: 11.12.4

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
    driver_config:
      box: opscode-ubuntu-12.04
      box_url: https://opscode-vm.s3.amazonaws.com/vagrant/boxes/opscode-ubuntu-12.04.box
      require_chef_omnibus: 11.12.4
      customize:
        memory: 2048
      network:
      - ["private_network", {ip: "192.168.33.33"}]

suites:
- name: artifactory
  run_list: ["recipe[artifactory]"]
